# Generated by Django 4.1.3 on 2023-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
